[package]
name = "earworm"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"

[dev-dependencies]
cpal = "0.15"
anyhow = "1.0"
crossterm = "0.28"
cargo-husky = { version = "1.5.0", features = ["precommit-hook", "run-cargo-test", "run-cargo-clippy", "run-cargo-fmt"] }
